### ISSUE TITLE
VSC vil ikke importere RestController

### ISSUE THREAD

**Issue by VitaBlixen** [Rotendahl/study-now-java#2]
Hej.
Jeg sidder fast i lektion 3 "Web".
Den vil hverken importere
org.springframework.web.bind.annotation.RestController
eller
org.springframework.web.bind.annotation.GetMapping
Hvilket betyder at den heller ikke vil anerkende @RestController eller @GetMapping.
Har du et bud på, hvordan jeg kan komme videre?

**Comment by Rotendahl** [comment]
Hej Vita. 
Det skal vi da have fundet en løsning på. 
Mit første bud ville være at projektet måske mangler web pakken.

Kan du se om det virker med setup herfra?
[demo.zip](https://github.com/Rotendahl/study-now-java/files/10272741/demo.zip)

**Comment by VitaBlixen** [comment]
Hej

Ja, det fungerer.
Tak for hjælpen 😊

Vh Vita

Sendt fra Mail<https://go.microsoft.com/fwlink/?LinkId=550986> til Windows

Fra: ***@***.***>
Sendt: 20. december 2022 22:20
Til: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Emne: Re: [Rotendahl/study-now-java] VSC vil ikke importere RestController (Issue #2)


Hej Vita.
Det skal vi da have fundet en løsning på.
Mit første bud ville være at projektet måske mangler web pakken.

Kan du se om det virker med setup herfra?
demo.zip<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRotendahl%2Fstudy-now-java%2Ffiles%2F10272741%2Fdemo.zip&data=05%7C01%7C%7C4cccea1817e64f0f867808dae2d003c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638071680286879774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wyt5hq9748VYfLT3XNqoq2v9FPgWlxk4Hbnzg%2BMIjWE%3D&reserved=0>

**Comment by Rotendahl** [comment]
Godt at høre!
