### ISSUE TITLE
500 internal Server error 

### ISSUE THREAD

**Issue by mikkeldeis** [Rotendahl/study-now-java#3]
Forsøger at Post via JSON
men får følgende error:
![image](https://user-images.githubusercontent.com/93324548/209135975-039837d3-9905-4368-8183-991833537db3.jpeg)

Kildekode:
![image](https://user-images.githubusercontent.com/93324548/209136200-e006e8d2-d685-4b75-931d-5716d14b6842.jpeg)
![image](https://user-images.githubusercontent.com/93324548/209136225-095428a2-2463-40dc-ade8-72e4e65b12bc.jpeg)
![image](https://user-images.githubusercontent.com/93324548/209136245-397bc86c-5c05-4ef6-a1d9-487e698d1d6d.jpeg)
![image](https://user-images.githubusercontent.com/93324548/209136271-f9f5a0f3-6900-4b34-bd4d-5c8b1aa8ae69.jpeg)

**Comment by Rotendahl** [comment]
Hej Mikkel. 
Det skal vi da have fixet. 
Kan du prøve at uploade enten din log eller koden som en zip fil?

**Comment by mikkeldeis** [comment]
[Calendar 2.zip](https://github.com/Rotendahl/study-now-java/files/10287031/Calendar.2.zip)

**Comment by Rotendahl** [comment]
Hej igen Mikkel. 
Prøv at ændre din `ActivityInput` kode til det her: 
```java
package com.example.Calendar;

import java.time.LocalDateTime;

public class ActivityInput {
    public String description;
    public LocalDateTime startDayWithTime;
    public int durationInHours;
    public int durationInMinutes;
}
```
Fejlen sker vidst fordi der er kommet ny version (3.0) af spring siden kurset blev optaget.

**Comment by mikkeldeis** [comment]
Det virkede. Tusinde tak for hjælpen.

God jul 🎅

**Comment by Rotendahl** [comment]
Godt at høre, og også glædelig jul til dig
